#!/usr/bin/env python3
"""Check official policy source pages and update data/source-watch.json.

This script uses only the Python standard library. It is designed for GitHub
Actions and GitHub Pages: no paid APIs, no secrets, no backend.
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from html.parser import HTMLParser
from pathlib import Path
from typing import Iterable
from urllib.error import HTTPError, URLError
from urllib.parse import urlparse
from urllib.request import Request, urlopen


ROOT = Path(__file__).resolve().parents[1]
POLICIES_PATH = ROOT / "data" / "policies.json"
WATCH_PATH = ROOT / "data" / "source-watch.json"
TIMEOUT_SECONDS = 25


class TextExtractor(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.title_parts: list[str] = []
        self.body_parts: list[str] = []
        self._skip_depth = 0
        self._in_title = False

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag in {"script", "style", "noscript", "svg"}:
            self._skip_depth += 1
        if tag == "title":
            self._in_title = True

    def handle_endtag(self, tag: str) -> None:
        if tag in {"script", "style", "noscript", "svg"} and self._skip_depth:
            self._skip_depth -= 1
        if tag == "title":
            self._in_title = False

    def handle_data(self, data: str) -> None:
        if self._skip_depth:
            return
        text = data.strip()
        if not text:
            return
        if self._in_title:
            self.title_parts.append(text)
        self.body_parts.append(text)

    @property
    def title(self) -> str:
        title = " ".join(self.title_parts).strip()
        return re.sub(r"\s+", " ", title)

    @property
    def body(self) -> str:
        body = " ".join(self.body_parts)
        return re.sub(r"\s+", " ", body).strip()


@dataclass(frozen=True)
class Source:
    party_id: str
    party_name: str
    url: str
    allowed_domains: tuple[str, ...]


def main() -> int:
    policies = read_json(POLICIES_PATH)
    previous = read_json(WATCH_PATH) if WATCH_PATH.exists() else {"sources": []}
    previous_by_url = {row.get("sourceUrl"): row for row in previous.get("sources", [])}

    checked_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    rows = []

    for source in collect_sources(policies):
        rows.append(check_source(source, previous_by_url.get(source.url), checked_at))

    WATCH_PATH.write_text(
        json.dumps(
            {
                "generatedAt": checked_at,
                "note": "Generated by scripts/check_sources.py from official party websites listed in data/policies.json.",
                "sources": rows,
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )
    return 0


def collect_sources(policies: dict) -> list[Source]:
    parties = {party["id"]: party for party in policies.get("parties", [])}
    seen: set[str] = set()
    sources: list[Source] = []

    configured = [
        (item["partyId"], item["url"])
        for item in policies.get("watchSources", [])
        if item.get("partyId") and item.get("url")
    ]
    policy_urls = [
        (policy["partyId"], policy["officialSource"]["url"])
        for policy in policies.get("policies", [])
        if policy.get("partyId") and policy.get("officialSource", {}).get("url")
    ]

    for party_id, url in [*configured, *policy_urls]:
        party = parties.get(party_id)
        if not party or url in seen:
            continue
        domains = tuple(party.get("officialDomains", []))
        if not is_allowed_official_url(url, domains):
            print(f"Skipping non-official or unapproved source for {party['name']}: {url}", file=sys.stderr)
            continue
        seen.add(url)
        sources.append(Source(party_id=party_id, party_name=party["name"], url=url, allowed_domains=domains))

    return sources


def check_source(source: Source, previous: dict | None, checked_at: str) -> dict:
    previous_hash = previous.get("contentHash") if previous else None

    try:
        html = fetch(source.url)
        parser = TextExtractor()
        parser.feed(html)
        content_hash = hashlib.sha256(parser.body.encode("utf-8")).hexdigest()
        changed = bool(previous_hash and previous_hash != content_hash)

        return {
            "party": source.party_name,
            "sourceUrl": source.url,
            "lastChecked": checked_at,
            "pageTitle": parser.title or fallback_title(source.url),
            "contentChanged": changed,
            "status": "ok",
            "contentHash": content_hash,
        }
    except (HTTPError, URLError, TimeoutError, UnicodeDecodeError) as error:
        return {
            "party": source.party_name,
            "sourceUrl": source.url,
            "lastChecked": checked_at,
            "pageTitle": previous.get("pageTitle") if previous else fallback_title(source.url),
            "contentChanged": None,
            "status": f"error: {error}",
            "contentHash": previous_hash,
        }


def fetch(url: str) -> str:
    request = Request(
        url,
        headers={
            "User-Agent": "nz-policy-tracker/1.0 (+https://github.com/)",
            "Accept": "text/html,application/xhtml+xml",
        },
    )
    with urlopen(request, timeout=TIMEOUT_SECONDS) as response:
        raw = response.read()
    return raw.decode("utf-8", errors="replace")


def is_allowed_official_url(url: str, domains: Iterable[str]) -> bool:
    parsed = urlparse(url)
    host = parsed.hostname or ""
    if parsed.scheme not in {"http", "https"}:
        return False
    return any(host == domain or host.endswith(f".{domain}") for domain in domains)


def fallback_title(url: str) -> str:
    parsed = urlparse(url)
    path = parsed.path.strip("/").replace("-", " ").replace("_", " ")
    return path.title() if path else parsed.hostname or "Untitled"


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


if __name__ == "__main__":
    raise SystemExit(main())
